config/routes.rb
Rails.application.routes.draw do
  root 'sajus#index'

  get 'sajus/saju'

  get 'sajus/jakmyung'

  get 'sajus/search'

  get 'sajus/detail'

  get 'sajus/payment'

  get 'sajus/qna'

  get 'sajus/seller'
  
  post 'sajus/newreview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/sajus_controller.rb
class SajusController < ApplicationController
  before_action :nav1, except: [:index, :seller]
  before_action :footer, except: [:qna]
  
  def index
  end

  def saju
  end

  def jakmyung
  end

  def search
  end

  def detail
    @review = Review.new
    @reviews = Review.all.order(id: :desc)
  end

  def payment
  end

  def newreview
    @review = Review.new(params.require(:review).permit(:user_id, :point, :content))
    @review.save
  end

  def seller
  end

  def qna
  end
  private
    def nav1
      @nav1 = true
    end

    def footer
      @footer = true
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sajus_helper.rb
module SajusHelper
end

app/views/application/_footer.html.erb
<footer class="footer">
    <div class="footer__bisinfo">
      <h6 class="footer--title"><br><br>(주) 아수라발발타 사업자 정보</h6>
      <p class="footer__bisinfo--row">(주) 아수라발발타 | 서울시 용산구</p>
      <p class="footer__bisinfo--row">대표 : 공동대표 | 개인정보관리자 : 공동</p>
      <p class="footer__bisinfo--row">사업자등록번호 : 123-45-67890 </p>
      <p class="footer__bisinfo--row">통신판매업신고 : 2018-서울 용산-01471호</p>
      <p class="footer__bisinfo--row">1544-6254 | mutjangee@asurabalbalta.com</p>
    </div>
    <div class="swiper-slide">
      <div class="d-flex justify-content-center bg-light">
        <div class="box3 mr-5 mt-3">
            <h6 class="text-center"><strong>카테고리</strong></h6>
            <h6 class="text-left">사주</h6>
            <h6 class="text-left">작명</h6>
            <h6 class="text-left">타로</h6>
            <h6 class="text-left">관상</h6>
            <h6 class="text-left">손금</h6>
            <h6 class="text-left">점성술</h6>
        </div>
        <div class="box3 mr-5 mt-3">
            <h6 class="text-center"><strong>의뢰인/전문가</strong></h6>
            <h6 class="text-left">구매 방법</h6>
            <h6 class="text-left">판매 시작하기</h6>
            <h6 class="text-left">전문가 수수료</h6>
        </div>
        <div class="box3 mr-5 mt-3">
            <h6 class="text-center"><strong>아수라발발타 정보</strong></h6>
            <h6 class="text-left">서비스소개</h6>
            <h6 class="text-left">아수라발발타팀</h6>
            <h6 class="text-left">언론보도</h6>
            <h6 class="text-left">인재채용</h6>
            <h6 class="text-left">이용약관</h6>
            <h6 class="text-left">개인정보취급방침</h6>
        </div>
        <div class="box3 mt-3">
            <h6 class="text-center"><strong>아수라발발타 안내</strong></h6>
            <h6 class="text-left">공지사항</h6>
            <h6 class="text-left">FAQ</h6>
            <h6 class="text-left">부당업체 신고하기</h6>
        </div>
    </div>
</footer>

app/views/application/_nav.html.erb
<header class="header">

    <div class="container">
      <div class="header__top">
        <div class="header__col">
          <a class="logo" href="/">
            <img class="logo__img" src="<%= asset_path "logo.png" %>" alt="logo">
          </a>
        </div>
        <div class="header__col">
          <div class="header__search-box">
            <input class="header__search" placeholder="어떤 서비스를 찾고계신가요?">
            <a href="search">
              <i class="fas fa-search"></i>
            </a>
          </div>
        </div>
        <div class="header__col">
          <a href="seller" class="header__item">판매 시작하기</a>
          <a href="#" class="header__item">로그아웃</a>
          <a href="/sajus/qna" class="header__item">자주 묻는 질문</a>
        </div>
      </div>
    </div>

    <div class="header__nav">
      <div class="nav__items">
        <a href="saju" class="nav__item">사주</a>
        <a href="jakmyung" class="nav__item">작명</a>
        <a href="#" class="nav__item">타로</a>
        <a href="#" class="nav__item">관상</a>
        <a href="#" class="nav__item">손금</a>
        <a href="#" class="nav__item">점성술</a>
      </div>
    </div>
</header>


<script>
  var pgurl = window.location.href.split("/")[4];
  console.log(window.location.href.split("/")[4])
  $(".nav__item").each(function() {
    if($(this).attr("href").split("/")[0] == pgurl) {
      console.log($(this).attr("href").split("/")[0])
      $(this).addClass("nav__item--active");
    }
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asurabalbalta</title>
      <script src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Do+Hyeon|Gothic+A1|Nanum+Gothic+Coding" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Do+Hyeon|Gothic+A1|Nanum+Gothic+Coding" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Nanum+Gothic+Coding" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.esm.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.esm.bundle.js"></script>
    <link rel="stylesheet" href="path/to/swiper.min.css">
  </head>

  <body>
    <%= render partial: "nav" if @nav1 %>
    <%= yield %>
    <%= render partial: "footer" if @footer %>
  </body>
</html>

app/views/sajus/index.html.erb
<div class="swiper-container">
    <div class="swiper-wrapper">
    <!-- 첫번째 페이지 -->
    <div class="swiper-slide landing-wrapper">
        <div class="d-flex flex-column">
          <div class="d-flex justify-content-between nanum">
          <a class="logo" href="/" style="margin-top: 50px; margin-left: 30px;">
            <img class="logo__img" src="<%= asset_path "logo-white.png" %>" alt="logo">
          </a>
            <div class=" mt-3 mr-3">
                <button type="button" class="btn btn-warning mr-2" style="margin-top: 50px !important"><%= link_to '판매 시작하기', sajus_seller_path, class:"text-dark" %></button>
                <button type="button" class="btn btn-warning" style="margin-top: 50px !important; margin-right: 5px !important;"><%= link_to '로그아웃', root_path, class:"text-dark" %></button>
                <button type="button" class="btn btn-warning" style="margin-top: 50px !important"><%= link_to '자주 묻는 질문', sajus_qna_path, class:"text-dark" %></button>
            </div>
          </div>
            <div class="d-flex flex-column align-items-center mb-5" style="margin-top: 300px;">
                <h1 class="text-center text-warning dohyeon mb-4">당신을 위한 맞춤 사주</h1>
                <form class="form-inline" action="<%=sajus_search_path%>" method="get">
                    <label class="sr-only" for="inlineFormInputName2">Name</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" placeholder="나의 #재물운 은?" id="inlineFormInputName2" style="width: 500px;">
                    <%= link_to "SEARCH", sajus_search_path, class:"btn btn-outline-warning" %>
                </form>
                <h6 class="text-center text-white-50 dohyeon mb-4" style="margin-top: 5px; margin-right:85px !important;">#연애운 &emsp;&emsp; #손금 보는 법 &emsp;&emsp; #사업 &emsp;&emsp; #작명 &emsp;&emsp; #올해 운세 &emsp;&emsp; #학업운</h6>
            </div>
        </div>
    </div>
        <!-- 두번째 페이지 -->
    <div class="swiper-slide">
        <div class="d-flex flex-column align-items-center mb-5 nanum land-wrapper">
            <h3 class="text-center text-warning mb-5" style="margin-top: 200px;">C A T E G O R Y</h3>
            <div class="d-flex">
                <a href="/sajus/saju"><div class="box mr-3">
                    <%= image_tag'bb.svg', class: "icon" %>
                    <p class="text-center text-white">사주</p>
                </div></a>
                <a href="/sajus/jakmyung"><div class="box mr-3">
                    <%= image_tag'name.svg', class: "icon" %>
                    <p class="text-center text-white">작명</p>
                </div></a>
                <div class="box mr-3">
                    <%= image_tag'ee.svg', class: "icon" %>
                    <p class="text-center text-white">관상</p>
                </div>
                <div class="box mr-3">
                    <%= image_tag'tarot.png', class: "icon" %>
                    <p class="text-center text-white">타로</p>
                </div>
                <div class="box">
                    <%= image_tag'hand.svg', class: "icon" %>
                    <p class="text-center text-white">손금</p>
                </div>
            </div>
            <div class="d-flex" style="margin-top: 30px;">
                <div class="box mr-3">
                    <%= image_tag'687824.svg', class: "icon" %>
                    <p class="text-center text-white">운세</p>
                </div>
                <div class="box mr-3">
                    <%= image_tag'687824.svg', class: "icon" %>
                    <p class="text-center text-white">신점</p>
                </div>
                <div class="box mr-3">
                    <%= image_tag'687824.svg', class: "icon" %>
                    <p class="text-center text-white">연애운</p>
                </div>
                <div class="box mr-3">
                    <%= image_tag'687824.svg', class: "icon" %>
                    <p class="text-center text-white">재물운</p>
                </div>
                <div class="box">
                    <%= image_tag'687824.svg', class: "icon" %>
                    <p class="text-center text-white">취업운</p>
                </div>
            </div>
        </div>
    </div>
        <!-- 세번째 페이지 -->
    <div class="swiper-slide  bg-light gothic">
      <p class="h3 text-center" style="margin-top: 180px">RANKING</p>
      <div class="d-flex justify-content-center" style="margin-top: 30px;">
        <div class="card" style="width: 19.1rem;">
            <%= image_tag'dddd.jpg', class: "card-image"%>
            <div class="card-body">
                <h5 class="card-title"><span class="badge badge-pill badge-warning">1</span> 운세집</h5>
                <p class="card-text">어디에서도 볼 수 없었던 최고급 일년운세를 제공합니다. 일년 총운과 함께 각 달의 운을 분야별로 상황에 맞게 구체적으로 풀이해 드립니다. 좋은 일과 나쁜 일을 미리 알려드립니다.</p>
            </div>
        </div>
        <div class="card" style="width: 19.1rem;">
            <%= image_tag'taro.jpg', class: "card-image" %>
            <div class="card-body">
                <h5 class="card-title"><span class="badge badge-pill badge-warning">2</span> 타로집</h5>
                <p class="card-text">500분의 실제 사례를 바탕으로 타로 해석을 통해 상담을 진행할 예정입니다. 털어놓지 못했던 고민들 허심탄회하게 얘기해주세요! 함께 천천히 고민을 해결해 보아요 :)</p>
            </div>
        </div>
        <div class="card" style="width: 19.1rem;">
            <%= image_tag'dot.jpg', class: "card-image" %>
            <div class="card-body">
                <h5 class="card-title"><span class="badge badge-pill badge-warning">3</span> 점집</h5>
                <p class="card-text">용한 점집, 유명한 점집 어디 없나? 답답하고 일이 꼬이고 풀리지 않을 때 해결책을 제시해 드립니다.</p>
            </div>
        </div>
      </div>
            <div class="d-flex justify-content-center" style="margin-top: 20px">
        <div class="box2 mr-5 mt-5">
            <h6 class="text-center"><strong>전문적인 서비스</strong></h6>
            <h6 class="text-center">각 분야 전문가의 차별화된 서비스를 이용해보세요</h6>
        </div>
        <div class="box2 mr-5 mt-5">
            <h6 class="text-center"><strong>만족도 높은 서비스</strong></h6>
            <h6 class="text-center">이용자이 직접 평가한 좋은 업체들을 보여드립니다</h6>
        </div>
        <div class="box2 mt-5">
            <h6 class="text-center"><strong>안전 거래 시스템</strong></h6>
            <h6 class="text-center">수많은 거래를 완료한 안전한 주문 시스템을 이용해보세요</h6>
        </div>
      </div>
    </div>
    <div class="swiper-slide nanum">
        <p class="h1 text-center mt-5" style="margin-top: 250px !important">C O N T A C T</p>
        <div class="d-flex flex-column justify-content-center align-items-center" >
          <table class="table table-borderless" style="width: 600px; margin-top: 50px;">
            <tbody>
                <tr><td class="h4"><span class="badge badge-pill badge-warning">1</span> (주) 아수라 발발타</td></tr>
                <tr><td class="h4"><span class="badge badge-pill badge-warning">2</span> 대표: 유현재, 고정정, 박지수, 손리동</td></tr>
                <tr><td class="h4"><span class="badge badge-pill badge-warning">3</span> 02 ) 1234 - 4567</td></tr>
                <tr><td class="h4"><span class="badge badge-pill badge-warning">4</span> 서울시 용산구 원효로</td></tr>
                <tr><td class="h4"><span class="badge badge-pill badge-warning">5</span> wisemanbest@gmail.com</td></tr>
            </tbody>
          </table>
        </div>
        <div></div>
    </div>
    </div>
    <div class="swiper-pagination" style="position:fixed;"></div>
</div>

<script src="path/to/jquery.js"></script>
<script src="path/to/swiper.jquery.min.js"></script>
<script>
        var mySwiper = new Swiper ('.swiper-container', {
          // Optional parameters
            direction: 'vertical',
            loop: true,

            // If we need pagination
            pagination: {
                el: '.swiper-pagination',
            },
            mousewheel: {
                invert: true,
                forceToAxis: true,
                releaseOnEdges: true,
                sensitivity: 10
            }




        });
        </script>

app/views/sajus/jakmyung.html.erb
<div class="container global-body">

    <main class="search">

      <section class="main">

        <div class="search__menu">
          <h2 class="search__title">작명</h2>

          <div class="menu__items">
            <h5 class="menu__category">카테고리</h5>
            <a href="#" class="menu__item">작명</a>
            <a href="#" class="menu__item">개명</a>
            <a href="#" class="menu__item">예명</a>
          </div>

        </div>

        <div class="search__cards">

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/dXK8g1528111041.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/CUDznB5mKFCc1527780731.jpg" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                신명철학관
              </div>
              <div class="card__text">
                온라인으로 작명과 개명을 도와드립니다.
              </div>
              <div class="card__price">120,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (11)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/Rblgg1524207280.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/q1R1W1523321157.jpg" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                rocnt2001
              </div>
              <div class="card__text">
                세상과의 첫 소통은 이름입니다. 좋은 기운을 담아 드립니다.
              </div>
              <div class="card__price">150,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (12)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/t8yXj1521090887.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/Um9UG1521087752.jpg" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                ncgold
              </div>
              <div class="card__text">
                (나눔작명원) 예쁜아기 예쁜이름 지어 드립니다.
              </div>
              <div class="card__price">10,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (4)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/l9EvB1525762787.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/ST5kG1524201312.JPG" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                yhcho0205
              </div>
              <div class="card__text">
                정확한 사주풀이를 통한 운세의 예측과 좋은 이름을 지어 드립 ...
              </div>
              <div class="card__price">20,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (9)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/F4zXa1520392287.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/iHYy91520351855.jpg" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                조은파
              </div>
              <div class="card__text">
                신생아 이름, 개명, 예명 성공하는 이름을 작명해 드립니다.
              </div>
              <div class="card__price">50,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (53)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/nZath1527565733." alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/SrFkw1527512237." alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                공리
              </div>
              <div class="card__text">
                사주상담, 타로상담, 궁합, 작명 등 속시원한 상담 해 드립니다.
              </div>
              <div class="card__price">5,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (53)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/XHhwV1520493708.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/MLIqD1520421949.jpg" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                태을철학
              </div>
              <div class="card__text">
                자연형상명리학으로 감명하고, 구정팔괘로 진퇴와 인연을 ...
              </div>
              <div class="card__price">30,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (53)
                </div>
              </div>
            </div>
          </div>

          <div class="search__card">
            <div class="card__pic">
              <img class="card__cover" src="https://d2v80xjmx68n4w.cloudfront.net/gigs/small/kNmS01518162672.jpg" alt="">
              <img class="card__profile-pic" src="https://d2v80xjmx68n4w.cloudfront.net/members/thumbs/rtJax1517811617.JPG" alt="">
            </div>
            <div class="card__content">
              <div class="card__title">
                qqwe007
              </div>
              <div class="card__text">
                운세, 사주, 궁합, 개명, 작명, 타로, 신점 상담 드립니다.
              </div>
              <div class="card__price">30,000원</div>
            </div>
            <div class="card__footer">
              <div class="footer__colum"><i class="far fa-heart"></i></div>
              <div class="footer__colum">
                <div class="stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  (53)
                </div>
              </div>
            </div>
          </div>

        </div>

      </section>

    </main>

  </div>

app/views/sajus/payment.html.erb
<h1>Sajus#payment</h1>
<p>Find me in app/views/sajus/payment.html.erb</p>

app/views/sajus/seller.html.erb
<header class="header header--seller">

    <div class="container">
      <div class="header__top">
        <div class="header__col header__col--white">
          <a class="logo" href="/">
            <img class="logo__img" src="<%= asset_path "logo-white.png"%>" alt="logo">
          </a>
        </div>
        <div class="header__col header__col--white">
          <a href="seller" class="header__item">판매 시작하기</a>
          <a href="#" class="header__item">로그아웃</a>
          <a href="/sajus/qna" class="header__item">자주 묻는 질문</a>
        </div>
      </div>
    </div>

    <div class="header__img">
      <h1 class="header__title">
        여러분의 가게를 손쉽게 홍보하세요
      </h1>
      <h4 class="header__subtitle">
        아수라발발타, 홍보와 피드백을 한번에!
      </h4>
      <div class="header__btns">
        <div class="header__btn">
          서비스 등록하기
        </div>
      </div>
    </div>

    <div class="header__info-container">
      <div class="header__info-box">
        <div class="info-box__column">
          <div class="info-box__title">
            일 평균 서비스 등록
          </div>
          <div class="info-box__content">
            71건
          </div>
        </div>
        <div class="info-box__column">
          <div class="info-box__title">
            총 거래 건수
          </div>
          <div class="info-box__content">
            5만 건+
          </div>
        </div>
        <div class="info-box__column">
          <div class="info-box__title">
            총 거래 금액
          </div>
          <div class="info-box__content">
            10억 원+
          </div>
        </div>
      </div>
    </div>

  </header>

  <div class="container global-body global-body--seller">

    <section class="seller__cards">
      <div class="seller__card">
        <img class="seller__card-pic" src="https://kmong.com/img/main/desktop/buyer_review_1.png" alt="">
        <div class="seller__card-content">
          <div class="seller__card-quotes-left">
            <i class="fas fa-lg fa-quote-left"></i>
          </div>
          <div class="seller__card-quotes-content">
            아수라발발타에 홍보하면서 매출이 200% 이상 올랐습니다.
            <br />
            아수라발발타가 없는 제 삶은 상상할 수도 없어요!
          </div>
          <div class="seller__card-quotes-right">
            <i class="fas fa-lg fa-quote-right"></i>
          </div>
          <div class="seller__card-person">
            <div class="seller__card-person-title">
              최규태님
            </div>
            <div class="seller__card-person-subtitle">
              수리수리마수리 대표
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="seller__cards">
      <div class="seller__card">
        <img class="seller__card-pic" src="https://kmong.com/img/main/desktop/buyer_review_2.png" alt="">
        <div class="seller__card-content">
          <div class="seller__card-quotes-left">
            <i class="fas fa-lg fa-quote-left"></i>
          </div>
          <div class="seller__card-quotes-content">
            아수라발발타를 통해 받은 피드백은 제 삶을 바꾸었습니다.
            <br />
            타로가 적성에 맞지 않다는 걸 깨달았어요! 고맙습니다!
          </div>
          <div class="seller__card-quotes-right">
            <i class="fas fa-lg fa-quote-right"></i>
          </div>
          <div class="seller__card-person">
            <div class="seller__card-person-title">
              김우진님
            </div>
            <div class="seller__card-person-subtitle">
              타로없인못살아 대표
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>